events {}

http {
    # This "upstream" block lists the two API copies. Nginx sends
    # requests to them in round-robin order: 1, 2, 1, 2, ...
    upstream leadtrack_backend {
        server api1:8000;
        server api2:8000;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://leadtrack_backend;
        }
    }
}
